#ifndef CONFIG_H
#define CONFIG_H

#define MAX_WEAR_COUNT (1UL << 32)
#define STEP_WEAR_COUNT (1UL << 10)
#define WEAR_STEP_NUMS (MAX_WEAR_COUNT / STEP_WEAR_COUNT)

#define SWAP_TABLE_BLOCK_NUM 8
#define SWAP_TABLE_PAGE_NUM 512

#define LOG_AREA_SIZE (1UL << 21)
#define LOG_TYPE_MAX_NUM 16

#define BLOCK_SWAP_TRANSACTION_INFO_NUM_PER_AREA 64
#define BLOCK_SWAP_TRANSACTION_LOG_AREA_SIZE (1UL << 21)

#define PAGE_SWAP_TRANSACTION_INFO_NUM_PER_AREA 64
#define PAGE_SWAP_TRANSACTION_LOG_AREA_SIZE (1UL << 21)

#define AVAIL_PAGE_TABLE_PAGE_GROUP_MAX_NUM 1024

#endif