#ifndef CONFIG_H
#define CONFIG_H

#define MAX_WEAR_COUNT (1UL << 32)
#define STEP_WEAR_COUNT (1UL << 10)
#define WEAR_STEP_NUMS (MAX_WEAR_COUNT / STEP_WEAR_COUNT)
#define ZONE_AVAIL_BLOCK_CACHE_NUM 128

#endif